### ISSUE TITLE
Uncaught InvalidAccessError on Chrome 41.0.2272.104 (64-bit) on Mac OS Yosemite v 10.10.1

### ISSUE THREAD

**Issue by fatihacet** [ajacksified/song-of-github#33]
When song is loaded browser throws an error. 

`Uncaught InvalidAccessError: Failed to execute 'start' on 'AudioBufferSourceNode': Start time must be a finite non-negative number: -0.256961`

Here is the screenshot.

![http://take.ms/Rp0cM](http://take.ms/Rp0cM)

**Comment by fatihacet** [comment]
I recorded a screencast. Embedded it here as gif, it may take time to load. In any case here is the actual URL http://recordit.co/i4YVj4py7e

![http://g.recordit.co/i4YVj4py7e.gif](http://g.recordit.co/i4YVj4py7e.gif)

**Comment by ssorallen** [comment]
Thanks. This looks like what was fixed in PR #32, but the Heroku site has not been updated with the fix. Are you looking at this on the production site, https://song-of-github.herokuapp.com/?

**Comment by ssorallen** [comment]
This should now be fixed. I just tested it and heard your song. :beers:

**Comment by fatihacet** [comment]
:+1:

**Comment by bojidar-bg** [comment]
Still fails on my end, should I open another issue?
(Fails for http://song-of-github.herokuapp.com/?username=est31)
